CREATE TABLE IF NOT EXISTS 'POSTS' (
    'POST_ID' INTEGER NOT NULL UNIQUE,
    'URL_ID' TEXT NOT NULL,
    'TITLE' TEXT NOT NULL,
    'AUTHOR' TEXT NOT NULL,
    'CREATED' TEXT NOT NULL,
    'UPDATED' TEXT NOT NULL,
    'POST' BLOB NOT NULL,
    'VISIBLE' INTEGER NOT NULL,
    PRIMARY KEY('POST_ID' AUTOINCREMENT)
);